
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COUT DOUBLE_LESS_THAN GREATER_THAN IDENTIFIER INCLUDE INT IOSTREAM LBRACE LESS_THAN LPAREN MAIN NAMESPACE NUMBER RBRACE RETURN RPAREN SEMICOLON STRING USINGprograma : include using funcion_maininclude : INCLUDE LESS_THAN IOSTREAM GREATER_THANusing : USING NAMESPACE IDENTIFIER SEMICOLONfuncion_main : INT MAIN LPAREN RPAREN LBRACE instrucciones RBRACEinstrucciones : instrucciones instruccion\n                         | instruccioninstruccion : impresion\n                       | retornoimpresion : COUT DOUBLE_LESS_THAN STRING SEMICOLONretorno : RETURN NUMBER SEMICOLON'
    
_lr_action_items = {'INCLUDE':([0,],[3,]),'$end':([1,7,24,],[0,-1,-4,]),'USING':([2,13,],[5,-2,]),'LESS_THAN':([3,],[6,]),'INT':([4,15,],[8,-3,]),'NAMESPACE':([5,],[9,]),'IOSTREAM':([6,],[10,]),'MAIN':([8,],[11,]),'IDENTIFIER':([9,],[12,]),'GREATER_THAN':([10,],[13,]),'LPAREN':([11,],[14,]),'SEMICOLON':([12,27,28,],[15,29,30,]),'RPAREN':([14,],[16,]),'LBRACE':([16,],[17,]),'COUT':([17,18,19,20,21,25,29,30,],[22,22,-6,-7,-8,-5,-10,-9,]),'RETURN':([17,18,19,20,21,25,29,30,],[23,23,-6,-7,-8,-5,-10,-9,]),'RBRACE':([18,19,20,21,25,29,30,],[24,-6,-7,-8,-5,-10,-9,]),'DOUBLE_LESS_THAN':([22,],[26,]),'NUMBER':([23,],[27,]),'STRING':([26,],[28,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'include':([0,],[2,]),'using':([2,],[4,]),'funcion_main':([4,],[7,]),'instrucciones':([17,],[18,]),'instruccion':([17,18,],[19,25,]),'impresion':([17,18,],[20,20,]),'retorno':([17,18,],[21,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> include using funcion_main','programa',3,'p_programa','combined.py',76),
  ('include -> INCLUDE LESS_THAN IOSTREAM GREATER_THAN','include',4,'p_include','combined.py',82),
  ('using -> USING NAMESPACE IDENTIFIER SEMICOLON','using',4,'p_using','combined.py',86),
  ('funcion_main -> INT MAIN LPAREN RPAREN LBRACE instrucciones RBRACE','funcion_main',7,'p_funcion_main','combined.py',90),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones','combined.py',94),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones','combined.py',95),
  ('instruccion -> impresion','instruccion',1,'p_instruccion','combined.py',102),
  ('instruccion -> retorno','instruccion',1,'p_instruccion','combined.py',103),
  ('impresion -> COUT DOUBLE_LESS_THAN STRING SEMICOLON','impresion',4,'p_impresion','combined.py',107),
  ('retorno -> RETURN NUMBER SEMICOLON','retorno',3,'p_retorno','combined.py',111),
]
